### ISSUE TITLE
Kdenlive on Arch Linux segfaults

### ISSUE THREAD

**Issue by qubodup** [mltframework/mlt-scripts#10]
Thank you for these scripts!

I seem to be able to compile on Arch Linux but it segfaults when I try to run the start-kdenlive script. I added gdb to it:
<pre>Starting program: /home/qubodup/kdenlive/20160102/bin/kdenlive 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe3aac700 (LWP 6756)]
Icon theme "oxygen" not found.
Icon theme "oxygen" not found.
Error: standard icon theme "oxygen" not found!

Program received signal SIGSEGV, Segmentation fault.
0x00007fffce008c34 in ?? () from /usr/lib/libQtGui.so.4
(gdb) bt
#0  0x00007fffce008c34 in ?? () from /usr/lib/libQtGui.so.4
#1  0x00007ffff7dea27a in call_init.part () from /lib64/ld-linux-x86-64.so.2
#2  0x00007ffff7dea38b in _dl_init () from /lib64/ld-linux-x86-64.so.2
#3  0x00007ffff7dee830 in dl_open_worker () from /lib64/ld-linux-x86-64.so.2
#4  0x00007ffff7dea124 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#5  0x00007ffff7dedfd1 in _dl_open () from /lib64/ld-linux-x86-64.so.2
#6  0x00007ffff62d3fc9 in ?? () from /usr/lib/libdl.so.2
#7  0x00007ffff7dea124 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#8  0x00007ffff62d45e1 in ?? () from /usr/lib/libdl.so.2
#9  0x00007ffff62d4061 in dlopen () from /usr/lib/libdl.so.2
#10 0x00007ffff672843f in mlt_repository_init (directory=0x55555606dfe0 "/home/qubodup/kdenlive/20160102/./lib/mlt")
    at mlt_repository.c:105
#11 0x00007ffff6727a84 in mlt_factory_init (directory=0x7fffffffea09 "/home/qubodup/kdenlive/20160102/./lib/mlt")
    at mlt_factory.c:184
#12 0x00007ffff64ea5b6 in Mlt::Factory::init(char const*) () from /home/qubodup/kdenlive/20160102/./lib/libmlt++.so.3
#13 0x00005555558bc2d1 in BinController::BinController (this=0x555556057110, profileName=...)
    at /home/qubodup/kdenlive/src/kdenlive/src/mltcontroller/bincontroller.cpp:36
#14 0x0000555555953997 in Core::initialize (this=0x555555d357a0) at /home/qubodup/kdenlive/src/kdenlive/src/core.cpp:60
#15 0x000055555592adf7 in MainWindow::MainWindow (this=0x555555d326a0, MltPath=..., Url=..., clipsToLoad=..., 
    parent=<optimized out>, __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
    at /home/qubodup/kdenlive/src/kdenlive/src/mainwindow.cpp:197
#16 0x00005555555f6db3 in main (argc=1, argv=<optimized out>) at /home/qubodup/kdenlive/src/kdenlive/src/main.cpp:117
</pre>

I do have oxygen installed though:
oxygen 5.5.2-1
oxygen-cursors 5.5.2-1
oxygen-icons 1:5.17.0-1
oxygen-kde4 5.5.2-1
ttf-oxygen 1:5.4.3-1

I can run kdenlive-git when I compile it on my own just using -DCMAKE_INSTALL_PREFIX= though.

Note: I downloaded and ran the build script from ~/kl/ rather than ~/kdenlive/ - it still created the latter. This is probably unrelated.

**Comment by bmatherly** [comment]
Are you building master? It would be best to start with the KDENLIVE developers. I see they just fixed a start up crash today:
https://quickgit.kde.org/?p=kdenlive.git&a=commit&h=d9fa09cce2db14e5750982340273feb5cde52966

Also, I see you are running with KDE4. I'm pretty sure that master no longer works with KDE4 - but I could be wrong.

**Comment by bmatherly** [comment]
Closing because this issue is stale.
