### ISSUE TITLE
build-melt.sh fails with sox dependency

### ISSUE THREAD

**Issue by shatgupt** [mltframework/mlt-scripts#12]
Is sox an optional dependency for melt?
Something is wrong here: https://github.com/mltframework/mlt-scripts/blob/master/build/build-melt.sh#L1036 . That block is checking `not disabled sox` then doing `mlt_format_optional` but then doing `DODIE=1`

**Comment by ddennedy** [comment]
It is optional. You are correct, and DODIE=1 should have been removed. It is now.
3f187e7181ac27cd193fbf474131e8565d519d3d
