### ISSUE TITLE
frei0r emboss seg fault melt

### ISSUE THREAD

**Issue by ydesgagn** [mltframework/mlt-scripts#19]
Hi,

We are using build-melt.sh v21 to build melt with all libraries. We discovered that when using frei0r emboss effect, melt will do a segmentation fault. With gdb, we clearly see it in in the emboss plugin.

So we went further and discovered that if using the same environment variables and commands that the script was using we can make it work.

The script set CFLAGS=. In such case emboss crash.

If we use the same commands but unset CFLAGS instead emboss will work fine.

Any clue?

**Comment by ddennedy** [comment]
There is no "set CFLAGS=." in this script:
https://github.com/mltframework/mlt-scripts/blob/master/build/build-melt.sh

There is "export CFLAGS=" on line 86. Did you comment that out?
If you did, what is the environment variable "CFLAGS" set to when you run build-melt.sh (not in the script, but in the shell or parent process that runs build-melt.sh)?

**Comment by ydesgagn** [comment]
I know, I meant export. CFLAGS is unset in my shell. The fix I did so far is to add a line before line 1113 to unset CFLAGS. But I still cannot explain why an empty CFLAGS can cause emboss to crash and not an unset CFLAGS.

**Comment by ydesgagn** [comment]
Closing. The `unset CFLAGS` change is working well for us in both kdenlive and melt scripts.
