### ISSUE TITLE
build-openshot.sh build-flowblade.sh segfault

### ISSUE THREAD

**Issue by kuh3h3** [mltframework/mlt-scripts#20]
tried to build on ubuntu 17.04.
build ok but when execute start-openshot , segfaults.
build-kdenlive.sh only build and run both  ok.

kuh3h3@reandro:~/openshot/20170924$ ls -al

drwxrwxr-x  7 kuh3h3 kuh3h3 4096  9월 24 04:21 .
drwxrwxr-x  4 kuh3h3 kuh3h3 4096  9월 24 04:06 ..
drwxr-xr-x  2 kuh3h3 kuh3h3 4096  9월 24 04:41 bin
drwxr-xr-x 14 kuh3h3 kuh3h3 4096  9월 24 04:28 include
drwxr-xr-x  5 kuh3h3 kuh3h3 4096  9월 24 04:41 lib
drwxrwxr-x 15 kuh3h3 kuh3h3 4096  9월 24 04:43 openshot
drwxrwxr-x  6 kuh3h3 kuh3h3 4096  9월 24 04:21 share
-rwxr-xr-x  1 kuh3h3 kuh3h3  705  9월 24 04:42 source-me
-rwxr-xr-x  1 kuh3h3 kuh3h3  910  9월 24 04:42 start-openshot

GNU gdb (Ubuntu 7.12.50.20170314-0ubuntu1.1) 7.12.50.20170314-git
(gdb) r openshot/openshot.py
Starting program: /usr/bin/python openshot/openshot.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
--------------------------------
   OpenShot (version 1.4.4~alpha1)
--------------------------------
Process no longer exists: 9887.  Creating new pid lock file.
[New Thread 0x7fffeaf4c700 (LWP 9951)]
[New Thread 0x7fffd5c99700 (LWP 9952)]
[New Thread 0x7fffcd002700 (LWP 9953)]
[New Thread 0x7fffcc801700 (LWP 9954)]

Detecting formats, codecs, and filters...
---
video_codecs:
  - a64multi
  - a64multi5
  - alias_pix
  - amv
  - apng
  - asv1
  - asv2
  - avrp
  - avui
  - ayuv
  - bmp
  - cinepak
  - cljr
  - dnxhd
  - dpx
  - dvvideo
  - ffv1
  - ffvhuff
  - fits
  - flashsv
  - flashsv2
  - flv
  - gif
  - h261
  - h263
  - h263p
  - huffyuv
  - jpeg2000
  - jpegls
  - ljpeg
  - mjpeg
  - mpeg1video
  - mpeg2video
  - mpeg4
  - msmpeg4v2
  - msmpeg4
  - msvideo1
  - pam
  - pbm
  - pcx
  - pgm
  - pgmyuv
  - png
  - ppm
  - prores
  - prores_aw
  - prores_ks
  - qtrle
  - r10k
  - r210
  - rawvideo
  - roqvideo
  - rv10
  - rv20
  - sgi
  - snow
  - sunrast
  - svq1
  - targa
  - tiff
  - utvideo
  - v210
  - v308
  - v408
  - v410
  - vc2
  - wrapped_avframe
  - wmv1
  - wmv2
  - xbm
  - xface
  - xwd
  - y41p
  - yuv4
  - zlib
  - zmbv
  - libtheora
  - libvpx
  - libvpx-vp9
  - libx264
  - libx264rgb
  - h264_nvenc
  - h264_vaapi
  - nvenc
  - nvenc_h264
  - nvenc_hevc
  - hevc_nvenc
  - hevc_vaapi
  - mjpeg_vaapi
  - mpeg2_vaapi
  - vp8_vaapi
  - vp9_vaapi
...
---
audio_codecs:
  - comfortnoise
  - s302m
  - aac
  - ac3
  - ac3_fixed
  - alac
  - dca
  - eac3
  - flac
  - g723_1
  - mlp
  - mp2
  - mp2fixed
  - nellymoser
  - opus
  - real_144
  - sonic
  - sonicls
  - truehd
  - tta
  - vorbis
  - wavpack
  - wmav1
  - wmav2
  - pcm_alaw
  - pcm_f32be
  - pcm_f32le
  - pcm_f64be
  - pcm_f64le
  - pcm_mulaw
  - pcm_s8
  - pcm_s8_planar
  - pcm_s16be
  - pcm_s16be_planar
  - pcm_s16le
  - pcm_s16le_planar
  - pcm_s24be
  - pcm_s24daud
  - pcm_s24le
  - pcm_s24le_planar
  - pcm_s32be
  - pcm_s32le
  - pcm_s32le_planar
  - pcm_s64be
  - pcm_s64le
  - pcm_u8
  - pcm_u16be
  - pcm_u16le
  - pcm_u24be
  - pcm_u24le
  - pcm_u32be
  - pcm_u32le
  - roq_dpcm
  - adpcm_adx
  - g722
  - g726
  - g726le
  - adpcm_ima_qt
  - adpcm_ima_wav
  - adpcm_ms
  - adpcm_swf
  - adpcm_yamaha
  - libmp3lame
  - libvorbis
...
---
formats:
  - a64
  - ac3
  - adts
  - adx
  - aiff
  - amr
  - apng
  - asf
  - ass
  - ast
  - asf_stream
  - au
  - avi
  - avm2
  - bit
  - caf
  - cavsvideo
  - crc
  - dash
  - data
  - daud
  - dirac
  - dnxhd
  - dts
  - dv
  - eac3
  - f4v
  - ffm
  - ffmetadata
  - fifo
  - filmstrip
  - fits
  - flac
  - flv
  - framecrc
  - framehash
  - framemd5
  - g722
  - g723_1
  - g726
  - g726le
  - gif
  - gsm
  - gxf
  - h261
  - h263
  - h264
  - hash
  - hds
  - hevc
  - hls
  - ico
  - ilbc
  - image2
  - image2pipe
  - ipod
  - ircam
  - ismv
  - ivf
  - jacosub
  - latm
  - lrc
  - m4v
  - md5
  - matroska
  - matroska
  - microdvd
  - mjpeg
  - mlp
  - mmf
  - mov
  - mp2
  - mp3
  - mp4
  - mpeg
  - vcd
  - mpeg1video
  - dvd
  - svcd
  - mpeg2video
  - vob
  - mpegts
  - mpjpeg
  - mxf
  - mxf_d10
  - mxf_opatom
  - null
  - nut
  - oga
  - ogg
  - ogv
  - oma
  - opus
  - alaw
  - mulaw
  - f64be
  - f64le
  - f32be
  - f32le
  - s32be
  - s32le
  - s24be
  - s24le
  - s16be
  - s16le
  - s8
  - u32be
  - u32le
  - u24be
  - u24le
  - u16be
  - u16le
  - u8
  - psp
  - rawvideo
  - rm
  - roq
  - rso
  - rtp
  - rtp_mpegts
  - scc
  - segment
  - stream_segment,ssegment
  - singlejpeg
  - smjpeg
  - smoothstreaming
  - sox
  - spx
  - spdif
  - srt
  - sup
  - swf
  - tee
  - 3g2
  - 3gp
  - mkvtimestamp_v2
  - truehd
  - tta
  - uncodedframecrc
  - vc1
  - vc1test
  - voc
  - w64
  - wav
  - webm
  - webm_dash_manifest
  - webm_chunk
  - webp
  - webvtt
  - wtv
  - wv
  - yuv4mpegpipe
  - alsa
  - fbdev
  - oss
  - sdl,sdl2
  - sndio
  - v4l2
  - xv
...
[New Thread 0x7fffc66c9700 (LWP 9955)]
[New Thread 0x7fffc5ec8700 (LWP 9956)]
state saved
[New Thread 0x7fffc56c7700 (LWP 9957)]
[New Thread 0x7fffc4eb9700 (LWP 9958)]
[New Thread 0x7fffc4e78700 (LWP 9959)]
[New Thread 0x7fff9bfff700 (LWP 9960)]
[New Thread 0x7fffc4677700 (LWP 9961)]
[New Thread 0x7fff9b7fe700 (LWP 9962)]

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
__GI___pthread_mutex_lock (mutex=0x0) at ../nptl/pthread_mutex_lock.c:67
67	../nptl/pthread_mutex_lock.c: 그런 파일이나 디렉터리가 없습니다.
(gdb) bt full
#0  0x00007ffff7bc2e90 in __GI___pthread_mutex_lock (mutex=0x0) at ../nptl/pthread_mutex_lock.c:67
        __PRETTY_FUNCTION__ = "__pthread_mutex_lock"
        type = <optimized out>
        id = <optimized out>
#1  0x00007ffff3835cba in XrmQGetResource () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#2  0x00007ffff3812156 in XGetDefault () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#3  0x00007ffff47d7a3f in  () at /usr/lib/x86_64-linux-gnu/libcairo.so.2
#4  0x00007ffff47d9f10 in  () at /usr/lib/x86_64-linux-gnu/libcairo.so.2
#5  0x00007ffff47ab6e7 in cairo_surface_get_font_options () at /usr/lib/x86_64-linux-gnu/libcairo.so.2
#6  0x00007ffff3b2d8db in  () at /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0
#7  0x00007ffff3b2dc39 in pango_cairo_create_context () at /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0
#8  0x00007ffff3b2dc80 in pango_cairo_create_layout () at /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0
#9  0x00007fffeb20782e in  () at /usr/lib/x86_64-linux-gnu/libgoocanvas.so.3
#10 0x00007fffeb2084d9 in  () at /usr/lib/x86_64-linux-gnu/libgoocanvas.so.3
#11 0x00007fffeb1fb82f in  () at /usr/lib/x86_64-linux-gnu/libgoocanvas.so.3
#12 0x00007fffeb1fc0ac in  () at /usr/lib/x86_64-linux-gnu/libgoocanvas.so.3
#13 0x00007fffeb1f23b6 in  () at /usr/lib/x86_64-linux-gnu/libgoocanvas.so.3
#14 0x00007fffeb1f23b6 in  () at /usr/lib/x86_64-linux-gnu/libgoocanvas.so.3
#15 0x00007fffeb21105f in  () at /usr/lib/x86_64-linux-gnu/libgoocanvas.so.3
#16 0x00007fffeb2115ec in goo_canvas_update () at /usr/lib/x86_64-linux-gnu/libgoocanvas.so.3
#17 0x00007fffeb211e8d in  () at /usr/lib/x86_64-linux-gnu/libgoocanvas.so.3
#18 0x00007ffff65cb22a in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff65cb5e0 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff65cb902 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff4e36457 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#22 0x00007ffff553e56f in  () at /usr/lib/python2.7/dist-packages/gtk-2.0/gtk/_gtk.so
#23 0x00005555556544ff in PyEval_EvalFrameEx ()
#24 0x0000555555654b9f in PyEval_EvalFrameEx ()
#25 0x0000555555654b9f in PyEval_EvalFrameEx ()
#26 0x000055555564d4e5 in PyEval_EvalCodeEx ()
#27 0x000055555564d289 in PyEval_EvalCode ()
#28 0x000055555567d13f in  ()
#29 0x0000555555678032 in PyRun_FileExFlags ()
#30 0x0000555555677b7e in PyRun_SimpleFileExFlags ()
#31 0x0000555555628a02 in Py_Main ()
#32 0x00007ffff78123f1 in __libc_start_main (main=
    0x555555628330 <main>, argc=2, argv=0x7fffffffc908, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffc8f8) at ../csu/libc-start.c:291
        result = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {0, -5990294497982931945, 93824993100288, 140737488341248, 0, 0, -465163824714998761, -465147249006---Type <return> to continue, or q <return> to quit---
863337}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7fffffffc920, 0x7ffff7ffe168}, data = {prev = 0x0, cleanup = 0x0, canceltype = -14048}}}
        not_first_call = <optimized out>
#33 0x000055555562822a in _start ()
(gdb) i r
rax            0x7ffff381b5e0	140737278752224
rbx            0x555556130310	93825004667664
rcx            0xec	236
rdx            0x7fffffffba1c	140737488337436
rsi            0x7fffffffba10	140737488337424
rdi            0x0	0
rbp            0x7fffffffba00	0x7fffffffba00
rsp            0x7fffffffb998	0x7fffffffb998
r8             0x7fffffffba00	140737488337408
r9             0x7ffff389ff87	140737279295367
r10            0x65	101
r11            0x0	0
r12            0x7fffffffb9fc	140737488337404
r13            0x5555562bf580	93825006302592
r14            0x555556ccf530	93825016853808
r15            0x0	0
rip            0x7ffff7bc2e90	0x7ffff7bc2e90 <__GI___pthread_mutex_lock>
eflags         0x10202	[ IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
(gdb) q
A debugging session is active.

	Inferior 1 [process 9946] will be killed.

Quit anyway? (y or n) y

**Comment by ddennedy** [comment]
build-openshot.sh is no longer supported as that project is no longer maintained and moved away from MLT. Feel free to open a different bug for build-flowblade.sh. Also, please be aware that these scripts tend to use git master of many projects, MLT git has added support for SDL2 but not yet in a backwards-compatible manner with apps assuming the availability of SDL1.2 MLT plugins. So, if your build picks up SDL2 instead of SDL1.2, you may have problems. SDL2 support is still in progress. Closing this with respect to OpenShot.
