### ISSUE TITLE
build-melt.sh fails

### ISSUE THREAD

**Issue by awright424** [mltframework/mlt-scripts#24]
build-melt.sh fails due to not being able to pull to movit.

``LOG: About to run command:
LOG: About to run command: mv eigen-eigen-10219c95fe65 eigen
LOG: Done getting or updating source for eigen
LOG: About to run command: popd
~/melt/src
LOG: Getting or updating source for movit - this could take some time
LOG: About to run command: pushd .
~/melt/src ~/melt/src
LOG: Cloning git sources for movit
LOG: About to run command: git --no-pager clone https://git.sesse.net/movit/
Cloning into 'movit'...
fatal: unable to access 'https://git.sesse.net/movit/': Could not resolve host: git.sesse.net
ERROR: Unable to git clone source for movit from https://git.sesse.net/movit/
LOG: Process has finished. Reason: FAILURE Some kind of error occured: Unable to git clone source for movit from https://git.sesse.net/movit/``

**Comment by ddennedy** [comment]
We are not responsible for sesse.net.  We have a nightly build server that clones sources multiple times a night and if something is enough of a nuisance with being unavailable, then we work on alternative source. sesse.net has not been too bad. For now, try again in a few hours or the next day.
