### ISSUE TITLE
Successful Compiliation But Missing Codecs

### ISSUE THREAD

**Issue by morphological** [mltframework/mlt-scripts#26]
Hey there, I was able to successfully compile kdenlive on Kubuntu 18.04 using the script. 

Upon launching kdenlive I get a warning that the following codecs are missing:
libx265, nvenc_h264, h264_nvenc

This is a problem, as I would like to use nvenc for rendering with my GPU.
I have used it with previous versions of kdenlive and it's awesome.

I am not sure how to solve this issue.
Already installed the nvenc-headers provided here: https://github.com/lutris/ffmpeg-nvenc/issues/22

**Comment by ddennedy** [comment]
The kdenlive build script is no longer intended to be used to build kdenlive for interactive usage since KDE5, but it is kept merely as a daily compile test.  Adding nvenc support is out-of-scope. See the kdenlive website to get or make your own build.

**Comment by morphological** [comment]
One final question.
When I try to render title clips the output simply says "Invalid".
I know that this is an issue with the kdenlivetitle module in mlt, however I could not find any related modules that weren't enabled during compiling.

Could you help me figure out how to compile mlt with title image support enabled?
