### ISSUE TITLE
https://github.com/breakfastquay/rubberband no longer has 'master' branch

### ISSUE THREAD

**Issue by MichaelJCole** [mltframework/mlt-scripts#34]
Hi, I'm trying to build Melt and got an error about this repo:

https://github.com/breakfastquay/rubberband

no longer having a 'master' branch, so the scripts failed.  

I set ENABLE_RUBBERBAND=0 as a workaround.  Thanks and have a great day!

**Comment by ddennedy** [comment]
Already fixed several months ago
https://github.com/mltframework/mlt-scripts/commit/d2e6ceddc7902ce1b5590776a9b207f84d180bb0
