### ISSUE TITLE
cannot find the gcc compiler

### ISSUE THREAD

**Issue by datietou** [mltframework/mlt-scripts#6]
when compile on ubuntu14.04, the script cannot find the compiler, the $PATH is not correct, I have already set the $PATH to the correct gcc-5.1.0/usr/bin, so build-shotcut.sh set the $PATH wrong anywhere?

**Comment by bmatherly** [comment]
Works for me on 14.04 using the standard gcc compiler. If you want to use a different compiler, you will have to modify the script.

**Comment by datietou** [comment]
I follow the tips this page said:
http://www.shotcut.org/bin/view/Shotcut/CrossCompile

use the gcc from mxe, and add the gcc to the $PATH, but build-shotcut.sh cannot find the correct environment $PATH value.

**Comment by bmatherly** [comment]
That page is for Shotcut. It will not work directly for the mlt scripts. You are on your own for this one, however, there may be some concepts that you could carry over. This tracker is for bugs, not support questions. If you come up with a working patch, feel free to send a pull request.
